### ISSUE TITLE
Ability to select a specific host/set of hosts for control plane / worker nodes

### ISSUE THREAD

**Issue by jamiemonserrate** [vmware-tanzu/cluster-api-provider-bringyourownhost#276]
**Describe the solution you'd like**
I would like the ability to select a certain host to be provisioned as a control plane v/s a worker node. 

If I have 2 sets of machines with different specs, I would like the ability to ensure that worker nodes are deployed on the more powerful machines, and the control plane nodes are provisioned on the smaller ones. 

**Anything else you would like to add:**
I personally think we do not need to go too fine grained. If we have the ability to assign a label filter for control plane and worker nodes, I think this should suffice.

**Comment by lwmqwer** [comment]
I remember that I had already implement it by using the label selector. We can label the byohost and select it by using the selector in the byomachine spec.

**Comment by dharmjit** [comment]
JFYI, @anusha94 and I have tested the below scenarios and they are working.

1. Multiple Workload Clusters from the capacity pool based on host label.
2. Selecting Control Plane and Worker Nodes based on host label.

Below is the selector applied to ByoMachineTemplate for `kubeadmControlPlane` and `MachineDeployment`.
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
  namespace: default
spec:
  template:
    spec:
      selector:
        matchLabels:
          "site": "A"
          "type": "worker"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  template:
    spec:
      selector:
        matchLabels:
          "site": "A"
          "type": "controlplane"
```
We will use this issue to discuss any other possible approaches to achieve the same.
